### ISSUE TITLE
Provision to add an image from web url

### ISSUE THREAD

**Issue by sankarvema** [csc/Hanlon#102] opened 2014-06-30 17:21 UTC
Hanlon image command provides options to add a local image file for OS and MK images. Most of the times these images are downloaded from internet (an url) to a local file and then uploaded by providing a reference to the local path. Extending the feature to directly reference the web url to upload image file would reduce effort.

This feature can help in managing the image from machines (mobile devices) which cannot hold the downloaded image on local store

**Comment by tjmcs** [comment] 2015-12-08 23:53
Closing as a duplicate of #244

**Closed by tjmcs** 2015-12-08 23:53 UTC
Labels: enhancement
